export const advisors = [
  {
    expertise: ['Hardware Guidance', 'Multisig Assistance'],
    languages: ['Portuguese', 'English', 'Español'],
    title: 'Leonardo - Diy Sec Lab',
    country: 'Brazil',
    description:
      'DIY Labs Introduction: DIY Security Lab is a Brazil-based fintech company specializing in ultra‑secure, open‑source tools for self‑custody of Bitcoin. Their flagship “Coldkit” — featuring the amnesic Krux device — enables fully air‑gapped, secure, and user‑verifiable transactions without relying on proprietary secure elements.\n \nThe company emphasizes transparency and trustlessness: all their recommended hardware and software are open-source.\n \nWith active tutorials, a D‑Academy educational platform, and global shipping, they cater to users seeking sovereignty and maximum protection for their bitcoin.',
    image: 'https://bitcoinkeeper.app/public_assets_email/advisor_leonardo.png',
    link: 'https://dseclab.io/en/pages/contato',
    duration: '30 mins',
    experience: '3.5 Years',
    timezone: 'GMT-3',
  },
  {
    expertise: ['Merchant Setup Support', 'Multisig Assistance'],
    languages: ['Norwegian', 'English'],
    title: 'Sondre - Satoshi Consult',
    country: 'Norway',
    description:
      'Satoshi Consult Introduction: Satoshi Consult is a Norwegian Bitcoin and Lightning Network consulting firm that serves both individuals and businesses, helping clients achieve secure self-custody, inheritance planning, and Lightning payments via tailored strategies . They specialize in cold storage and multisig solutions to ensure clients retain full control of their keys (“Not your keys. Not your coins”), and also support merchant onboarding with Bitcoin point-of-sale systems and Lightning node integration.\n \nAdditionally, Satoshi Consult offers expert guidance on Bitcoin privacy, cybersecurity resilience, tax/accounting considerations, and delivers customized keynotes and workshops to educate teams on both foundational and advanced Bitcoin topics.',
    image: 'https://bitcoinkeeper.app/public_assets_email/advisor_sondre.png',
    link: 'https://www.satoshiconsult.com/services/initial-consultation',
    duration: '45 mins',
    experience: '4 Years',
    timezone: 'CET',
  },
  {
    expertise: ['Multisig Assistance', 'Legal Advisory', 'Inheritance Planning'],
    languages: ['English', 'Hindi'],
    title: 'Bitcoincierge',
    country: 'India',
    description:
      "Bitcoincierge is an India‑based Bitcoin advisory and mentorship firm dedicated to guiding clients through every stage of their Bitcoin journey—from first purchase and custody solutions to inheritance planning and tax compliance .\n\nTheir experienced mentors assist with secure wallet selection, cold and multi‑sig storage strategies, and navigating India's legal/regulatory landscapes. \n\nThey run meetups and masterclasses across Mumbai, Delhi and Goa, fostering community education and practical learning. Looking ahead, Bitcoincierge is expanding its advisory services to support corporate treasury teams in integrating Bitcoin into their balance sheets.",
    image: 'https://bitcoinkeeper.app/public_assets_email/Bitcoincierge.png',
    link: 'https://www.bitcoincierge.in/#mentor-section',
    duration: '45 mins',
    experience: '3 Years',
    timezone: 'IST',
  },
  {
    expertise: ['Multisig Assistance', 'Inheritance Planning', 'Treasury Advisory'],
    languages: ['English', 'Hindi'],
    title: 'Keeper Private',
    country: 'UK',
    description:
      'Bitcoin Keeper is a Bitcoin-focused, open-source key management app designed for hodlers who want to secure and grow their BTC over time . It supports hot wallets, multi-key/miniscript vaults, hardware-wallet integration, UTXO management, and even inheritance tools—all wrapped in a user-friendly mobile and desktop experience.\n\nOur Keeper Private concierge service caters to high-net-worth individuals and institutions, offering complete setup assistance, hardware kits, periodic check-ins, and inheritance planning.',
    image: 'https://bitcoinkeeper.app/public_assets_email/KeeperPrivate.png',
    link: 'https://bitcoinkeeper.app/private/',
    duration: '30 mins',
    experience: '4 Years',
    timezone: 'BST',
  },
  {
    expertise: ['Multisig Assistance', 'Inheritance Planning'],
    languages: ['English', 'Hindi'],
    title: 'Abhilash Nair',
    country: 'India',
    description:
      'Abhilash Nair is an independent Bitcoin consultant helping individuals and businesses confidently navigate self-custody and secure wealth preservation. He specializes in guiding clients through exchange offboarding, setting up resilient custody frameworks, and simplifying the complexities of Bitcoin ownership. His approach is hands-on, privacy-focused, and tailored to each client’s unique needs.\n\nAbhilash also offers advanced consulting on multi-signature setups, inheritance planning, and long-term security strategies. With experience in Bitcoin Keeper and broader industry projects, he brings a deep understanding of tools, best practices, and risk mitigation. Clients value his ability to make Bitcoin approachable while ensuring robust protection of their holdings.',
    image: 'https://bitcoinkeeper.app/public_assets_email/advisor_abhilash.png',
    link: 'https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ0dc3JVJzTz_-EWm7GsHWPk0bH4ugbvvy-K6HnP4mDVC5LYm-FQk2nlimgBrnRO1cEHzFcUfTR0',
    duration: '30 mins',
    experience: '4 Years',
    timezone: 'IST',
  },
  {
    expertise: ['Merchant Setup Support', 'Multisig Assistance'],
    languages: ['French', 'Dutch', 'German'],
    title: 'Rob - Bitsaga',
    country: 'Belgium',
    description:
      'Bitsaga offers tailored services to help individuals and businesses take full control of their Bitcoin. They assist with secure exchange offboarding, automated cost-averaging, and security audits that improve self-custody. Each service is designed to simplify the process and give clients the confidence to manage their Bitcoin safely. \n\nTheir signature service focuses on building strong multi-signature setups. Clients get expert help with hardware wallets, backups, and recovery planning to remove single points of failure. Bitsaga also provides custom consulting, workshops, and training to address unique needs and strengthen Bitcoin security.',
    image: 'https://bitcoinkeeper.app/public_assets_email/advisor_rob.png',
    link: 'https://cal.com/bitsaga/30min?user=bitsaga',
    duration: '30 mins',
    experience: '4 Years',
    timezone: 'CET',
  },
  {
    expertise: ['Multisig Assistance', 'Inheritance Planning', 'Treasury Advisor'],
    languages: ['English'],
    title: 'Keeper in-house advisory',
    country: 'UK',
    description:
      'Your dedicated in-house advisor provides hands-on technical guidance for securing your bitcoin. Get expert help with:\n• Multisig setup & configuration \n• Hardware wallets & self-custody best practices \n• Inheritance planning support \n• Connections to relevant external experts when needed',
    image: 'https://bitcoinkeeper.app/public_assets_email/advisor_keeper.jpg',
    link: 'mailto:keeper@bithyve.com',
    duration: '30 mins',
    experience: '5+ Years',
    timezone: 'GMT',
  },
];
